apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  labels: { app: mern, tier: frontend }
spec:
  replicas: 2
  selector:
    matchLabels: { app: mern, tier: frontend }
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  template:
    metadata:
      labels: { app: mern, tier: frontend }
    spec:
      containers:
        - name: frontend
          # CHANGE THIS IMAGE
          image: munitkumar/csfrontend:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 80, name: http }]
          env:
            # if your FE needs the API URL at runtime (served by Nginx)
            - name: API_BASE_URL
              value: "http://be:3000"
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits:   { cpu: "300m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: fe
  labels: { app: mern, tier: frontend }
spec:
  type: ClusterIP
  selector: { app: mern, tier: frontend }
  ports:
    - name: http
      port: 80
      targetPort: http
