apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host:         # 
      http:
        paths:
          - path: /(api/.*)
            pathType: Prefix
            backend:
              service:
                name: be
                port: { number: 3000 }
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: fe
                port: { number: 80 }
